name: Build docker images
on:
  schedule:
    - cron: '0 8 * * *'
  push:
    paths:
      - '.github/workflows/build.yaml'
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  check:
    name: 'Check remote repo commit'
    outputs:
      local_sha1: ${{ steps.fetch_locale.outputs.sha1 }}
      remote_sha1: ${{ steps.fetch_remote.outputs.sha1 }}
    runs-on: ubuntu-latest
    steps:
      - name: Cache Commit
        id: cache-commit
        uses: actions/cache@v4
        with:
          path: cache/commit
          key: commit

      - name: Create cache path
        run: mkdir -p cache/commit

      - name: Fetch locale cache commit
        id: fetch_locale
        run: echo "sha1=$(cat cache/commit/sha1 || echo 0)" >> "$GITHUB_OUTPUT"

      - name: Fetch remote repo latest commit
        id: fetch_remote
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/home-assistant/brands/commits/heads/master > /tmp/gh_result
          jq -r .sha1 /tmp/gh_result > cache/commit/sha1
          echo "sha1=$(cat cache/commit/sha1)" >> "$GITHUB_OUTPUT"

  build:
    name: 'Build Docker Image'
    needs: check
    if: needs.check.outputs.local_sha1 != needs.check.outputs.remote_sha1
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build brands
        run: ./build.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        run: docker buildx build --platform linux/arm64,linux/amd64 --tag hill98/home-assistant-brands:latest --push .
