name: Build docker images
on:
  schedule:
    - cron: '0 8 * * *'
  push:
  workflow_dispatch:

jobs:
  build:
    name: 'Build Docker Image'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Fetch remote repo latest commit
        id: fetch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/home-assistant/brands/commits/heads/master > gh_result
          jq -r .sha gh_result
          echo "sha1=$(jq -r .sha gh_result)" >> "$GITHUB_OUTPUT"

      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: cache/commit
          key: commit-${{ steps.fetch.outputs.sha1 }}

      - name: Build brands
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: ./build.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: docker buildx build --platform linux/arm64,linux/amd64 --tag hill98/home-assistant-brands:latest --push .

      - name: Save state to cache
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: install -D -m 0644 -T -v /dev/stdin cache/commit/state <<< "ok"
